---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tibble)
library(dplyr)
library(ggplot2)
library(dslabs)
library(scales)
```


1
glimpse(gapminder)

1.a

```{r}
gapminder%>%
  arrange(country)%>%
  select(country, year,gdp)%>%
  mutate(previous_year_gdp= lag(gdp, order_by = country))
```



1.b



```{r}
gapminder%>%
  select(continent, year,gdp)%>%
  group_by(continent, year) %>%
  summarise_at(vars(gdp),sum,na.rm=TRUE)%>%
  mutate(previous_year_gdp= lag(gdp))%>%
  mutate(change=(gdp/previous_year_gdp-1))
```




```{r}

glimpse(gapminder)

gapminder%>%
  select(continent, year,gdp)%>%
  group_by(continent, year) %>%
  summarise_at(vars(gdp),sum,na.rm=TRUE)%>%
  mutate(previous_year_gdp= lag(gdp))%>%
  mutate(change=(gdp/previous_year_gdp-1))%>%
  ggplot(aes(x=year,y=change,group=continent,color=continent))+
  geom_line()+
  scale_y_continuous(name="Annual GDP change", limits=c(-0.05,0.1))
```
1.1.2

```{r}
gapminder %>%
  arrange(country)%>%
  select(country, year,gdp,region)%>%
  mutate(py_gdp = lag(gdp))%>%
  mutate(growth=gdp/py_gdp-1)%>%
  group_by(region)%>%
  mutate(mgr=mean(growth,na.rm=TRUE))%>%
  mutate(diff = growth-mgr )%>%
  arrange(diff)
```
1.1.3


```{r}
gapminder %>%
  select(country, year,gdp,region)%>%
  group_by(country)%>%
  mutate(py_gdp = lag(gdp))%>%
  mutate(growth=gdp/py_gdp-1,na.rm=TRUE)%>%
  group_by(region)%>%
  mutate(mgr=mean(growth,na.rm=TRUE))%>%
  mutate(bool_var = growth>mgr,na.rm=TRUE)%>%
  group_by(country)%>%
  summarise(summa=sum(bool_var,na.rm = TRUE))%>%
  arrange(desc(summa))



```
1.2.1


```{r}
gapminder%>%
  filter(country=='China')

  ggplot(gapminder, aes(x=infant_mortality))+
  geom_histogram(binwidth = 1)
              
```

